apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: Test-Python 
  janus-idp.io/tekton: Test-Python
  backstage.io/kubernetes-id: Test-Python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: Test-Python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  