apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Test-Python-gitops
  description: This is GitOps manifest for Test-Python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: Test-Python
    janus-idp.io/tekton: Test-Python 
    backstage.io/kubernetes-id: Test-Python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:Test-Python
